### ISSUE TITLE
Hello, could anyone help me to configure node-merged-pool and what are the requirements to install on ubuntu 14.04?

### ISSUE THREAD

**Issue by ghost** [UNOMP/node-merged-pool#9]
Hello, could anyone help me to configure node-merged-pool and what are the requirements to install on ubuntu 14.04?

I have tried the following:

Apt-get install build-essential libtool autotools-dev autoconf pkg-config libssl-dev

Apt-get install libboost-all-dev git npm nodejs nodejs-legacy libminiupnpc-dev redis-server

Add-apt-repository ppa: bitcoin / bitcoin

Apt-get update
Apt-get install libdb4.8-dev libdb4.8 ++ - dev
Curl https://raw.githubusercontent.com/creationix/nvm/v0.16.1/install.sh | Sh
Source ~ / .profile
Nvm install 0.12
Nvm use 0.12

Git clone https://github.com/UNOMP/node-merged-pool/

Cd node-merged-pool /

Npm update

Then I tried to set up the example.js file
According to the two scrypt coins that I want to mine in a fused way, changing the rcp ports, username, password, names, symbols to each daemon respectively,
I have replaced the demon wallet of the main currency.
I have adjusted the difficulty of the ports,
But I do not know where else to configure. Or if I lack any dependency
`When I start
Node example.js
Tells me that there is an error, and is that there is no instruction here that says how to use this merged mining module

When it says that I have to create the settings for each currency, this must be done in the same file example.js ?, since I do not see any folder that says coins, it should be renamed to file example.js if that is exactly why?
And also I came up with a doubt I saw in file example.js the following:

Data object contains:
    Job: 4, // job job ID stratum
    Ip: '71 .33.19.37 ', // client IP address
    Port: 3333, // the client port
    Worker: // name of worker stratum 'matt.worker1'
    Height: 443 795, // block height
    BlockReward: 5000000000, // the number of satoshis received as payment for the solution of this block
    Difficulty: 64, // difficulty worker stratum
    ShareDiff: 78, // actual quota difficulty
    BlockDiff: 3349, // difficulty block set for quota fill
    BlockDiffActual: 3349 // actual difficulty for this block
    // Also known as the block solution - set whether the block was found
    BlockHash: '110c0447171ad819dd181216d5d80f41e9218e25d833a2789cb8ba289a52eee4',
    // Exists if "emitInvalidBlockHashes" has the true value
    BlockHashInvalid: '110c0447171ad819dd181216d5d80f41e9218e25d833a2789cb8ba289a52eee4'
    // TxHash is the hash coinbase transaction of the block
    TxHash: '41bb22d6cc409f9c0bae2c39cecd2b3e3e1be213754f23d12c5d6d2003d59b1d,
    Error: "low difficulty quota '// sets whether the quota is rejected for some reason

Do you have to configure something here? For example the IP, would the public IP of my server?
The name of the worker?
Block height

This here
 Difficulty: 64, // difficulty worker stratum
    ShareDiff: 78, // actual quota difficulty
    BlockDiff: 3349, // difficulty block set for quota fill
    BlockDiffActual: 3349 // actual difficulty for this block
    // Also known as the block solution - set whether the block was found
    BlockHash: '110c0447171ad819dd181216d5d80f41e9218e25d833a2789cb8ba289a52eee4',
    // Exists if "emitInvalidBlockHashes" has the true value
    BlockHashInvalid: '110c0447171ad819dd181216d5d80f41e9218e25d833a2789cb8ba289a52eee4'
    // TxHash is the hash coinbase transaction of the block
    TxHash: '41bb22d6cc409f9c0bae2c39cecd2b3e3e1be213754f23d12c5d6d2003d59b1d,
    Error: "low difficulty quota '// sets whether the quota is rejected for some reason

**Comment by Infernoman** [comment]
This is not a node-merged-pool issue. It is a configuration issue. Please read the README. The content your speaking about is commented out, which shows the data that the worker is submitting.
